# Generated by Django 4.2.6 on 2023-10-09 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(limit_value=120, message='Description cannot be longer than 120 characters.')]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Quantity should be more than or equal to 0.'), django.core.validators.MaxValueValidator(limit_value=100, message='Quantity should be less than or equal to 100.')]),
        ),
    ]
